split out release archives and fix security risk in workflow
Signed-off-by: George Vauter <gvauter@redhat.com>

diff --git a/.github/workflows/goreleaser-workflow.yml b/.github/workflows/goreleaser-workflow.yml
--- a/.github/workflows/goreleaser-workflow.yml
+++ b/.github/workflows/goreleaser-workflow.yml
@@ -41,14 +41,22 @@ jobs:
     - name: Set env
       run: |
         if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
-          echo "RELEASE_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
+          if ! grep -E '^v[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' <<<"${INPUT_TAG}"; then
+            echo 'Invalid tag format. Must be semver with only major, minor, and patch, e.g. v1.2.3'
+            exit 1
+          fi
+          echo "RELEASE_VERSION=${INPUT_TAG}" >> $GITHUB_ENV
         else
           echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
         fi
+      env:
+        INPUT_TAG: ${{ github.event.inputs.tag }}
     - name: Create tag for manual dispatch
       if: github.event_name == 'workflow_dispatch'
       run: |
-        git tag ${{ github.event.inputs.tag }}
+        git tag "${INPUT_TAG}"
+      env:
+        INPUT_TAG: ${{ github.event.inputs.tag }}
     - name: Delete non-semver tags
       run: 'git tag -d $(git tag -l | grep -v "^v") || true'
     - name: Run GoReleaser on tag
