fix: allow strings in sem ver tags for goreleaser
Signed-off-by: George Vauter <gvauter@redhat.com>

diff --git a/.github/workflows/goreleaser-workflow.yml b/.github/workflows/goreleaser-workflow.yml
--- a/.github/workflows/goreleaser-workflow.yml
+++ b/.github/workflows/goreleaser-workflow.yml
@@ -41,8 +41,8 @@ jobs:
     - name: Set env
       run: |
         if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
-          if ! grep -E '^v[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$' <<<"${INPUT_TAG}"; then
-            echo 'Invalid tag format. Must be semver with only major, minor, and patch, e.g. v1.2.3'
+          if ! grep -E '^v[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*(-[a-zA-Z0-9]+(\.[a-zA-Z0-9]+)*)?$' <<<"${INPUT_TAG}"; then
+            echo 'Invalid tag format. Must be semver, e.g. v1.2.3 or v2.0.0-alpha.1'
             exit 1
           fi
           echo "RELEASE_VERSION=${INPUT_TAG}" >> $GITHUB_ENV
